template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  The state of the PoE2 economy is currently very chaotic and messy due to the late-league state and the large number of highly invasive changes.
  
  This patch focuses on hardening the filter economy based tiering to deal with such messy states and also prepare it for the upcoming league.
  
  ## CHANGES:
  - Massive overhauls to the economy based tiering. Guardrails, aspects, threshold adjustments, additional sources etc. have all been used to improve the current system
  - Vastly adjusted the practical (economy versions only) tiering for: currency, uniques, omens, socketables, fragments
  - The socketable item tiering now treats runes, talismans and soul cores in the same way.
  - Reworked leveling rune implementation and tiering
  - Other Minor adjustments
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
