template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  All of the Dawn of the Hunt content and also improves upon the existing sections, such as economy tiering, gems etc.
  It also comes with a new style: Zen! Happy hunting!
  
  ## NEW CONTENT:
  - Added all of the dawn of the hunt basetypes
  - Added a kalandra jewellery section
  - Added new style: Zen! Minimal, clean and great for customizing.
  - Added a new vault key section (reqliquary keys). They all make the SHWING sound for now!
  - Added spear and buckler relevant sections and classes
  - Renamed all the advanced and expert bases according to GGG's migration table
  - Added the new omens to the tierlist. I suspect they're mostly there to clutter up the omen pool, since every ritual now has an omen. They should be all fairly low tier according to poe2db description.
  
  ## LARGE REWORKS:
  - Reworked the gem section
  - Reworked the socketable section (merged it soulcores and runes and added better campaign overrides)
  
  ## TIERING:
  - Retiered all uniques and added some to the early league tier
  - Retiered all the currencies by hand for the new league (until economy data is available and reliable)
  - Moved many S tier items into A tier (until economy data is available and reliable)
  - Moved catalysts up by one tier
  - Moved stellar amulet a tier down in temrs of chancing. Moved sapphire ring a tier down.
  - Adjusted the basetype tiering
  
  ## COMING SOON:
  - Added advanced economy tiering sections and rules for SC/HC. THose will be enabled in a couple of days, once I'm sure it'll work (too risky for release)
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
